on: [ push, pull_request ]

jobs:
  test:
    runs-on: self-hosted
    name: Run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.0.0'
      - run: npm install

      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    name: Compile Typescript
    needs: [ test ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.0.0'
      - run: npm install
      - name: Typescript compiler
        uses: iCrawl/action-tsc@v1

  automerge:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
