on: [ push, pull_request ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build & run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.0.0'
      - run: npm install
      - name: Typescript compiler
        run: npm run compile
      - name: Run tests
        run: npm test
