on: [ push, pull_request ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build & run tests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.0.0'
      - run: npm install
      - name: Typescript compiler
        uses: stepek/tsc-action@master
      - name: Run tests
        run: npm test


  automerge:
    needs: [ build-and-test ]
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
